services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dln
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  db-migrate:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_APP_DIR: "packages/db/"
        NODE_APP_NAME: "@debridge-test/db"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dln
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./apps/indexer:/usr/src/app
    restart: "no"
    command: "npm run migrate:latest"

  indexer:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_APP_DIR: "apps/indexer/"
        NODE_APP_NAME: "@debridge-test/indexer"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dln
      SOLANA_RPC_URL: https://mainnet.helius-rpc.com/?api-key=e53b6dd2-399d-45d6-b324-1fdccd6a1ac5
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    volumes:
      - ./apps/indexer:/usr/src/app

  aggregator:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_APP_DIR: "apps/aggregator/"
        NODE_APP_NAME: "@debridge-test/aggregator"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dln
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    volumes:
      - ./apps/aggregator:/usr/src/app

  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_APP_DIR: "apps/api/"
        NODE_APP_NAME: "@debridge-test/api"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dln
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    ports:
      - "4000:4000"
    volumes:
      - ./apps/api:/usr/src/app

# frontend:
#   build: ./apps/frontend
#  ports:
#      - "3000:3000"
#    volumes:
#      - ./apps/frontend:/usr/src/app
#    command: ["npm", "run", "dev"]

volumes:
  db_data:
